version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    networks:
      - application_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - .:/var/www
      - ./docker/logs:/var/log/nginx
    links:
      - php

  php:
    container_name: php
    restart: always
    networks:
      - application_network
    build:
      ./docker/images/php
    volumes:
      - .:/var/www:cached
    links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.2-alpine
    restart: always
    networks:
      - application_network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/volumes
    ports:
      - "54321:5432"

volumes:
  db:
    external: true

networks:
  application_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.18.0/24